### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [josephjguerra/dasmoto#6]
Summary Grade: Satisfactory

Good job with your code! Everything loads fine but everything is on the same line so it's hard to check how well you organized your code. But, good decisions on the classes and ids name. It makes it very clear what its purpose is and makes grouping your sections very effective. These organizational skills come in handy as you expand your code. 

I included a few notes in both the html and css files for you to think more critically about. First, try to save your images locally instead of adding a link. Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. Also, make sure to use the html & sign instead of just &, which is `&amp;.` This is just a convention. Finally, make sure to check your files after you upload onto github to make sure everything looks the way you want to.

**Comment by josephjguerra** [comment]
Thank you for the review @sangjunp4rk ! All recommendations corrected, a pushed to gh-pages: http://josephjguerra.com/dasmoto/
